/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/soldier/soldier-soldier.lh
 */
export class SoldierSoldierUIBase extends Laya.Box {
}

