/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { ImageBar } from "../../misc/ImageBar";

/**
 * resources/prefab/soldier/soldier-train-item.lh
 */
export class SoldierTrainItemUIBase extends Laya.Box {
    public imgIcon!: Laya.Image;
    public labelLv!: Laya.Label;
    public imgBar!: ImageBar;
    public labelVal!: Laya.Label;
    public btnUpLv!: Laya.Button;
    public labelMoney!: Laya.Label;
}

