/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { HomeMonyeItemUI } from "../home/HomeMonyeItemUI";

/**
 * resources/prefab/soldier/soldier-train.lh
 */
export class SoldierTrainUIBase extends Laya.Box {
    public listAttr!: Laya.List;
    public moneyItem!: HomeMonyeItemUI;
}

