/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/soldier/soldier.lh
 */
export class SoldierUIBase extends Laya.Box {
    public tab!: Laya.Tab;
    public viewStack!: Laya.ViewStack;
}

