/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/soldier/soldier-train.lh
 */
export class SoldierTrainUIBase extends Laya.Box {
    public listAttr!: Laya.List;
}

