/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { VirtuallyListUI } from "../common/VirtuallyListUI";

/**
 * resources/prefab/chat/chat.lh
 */
export class ChatUIBase extends Laya.Dialog {
    public btnSend!: Laya.Button;
    public btnEmoji!: Laya.Button;
    public inputMsg!: Laya.TextInput;
    public virtuallyList!: VirtuallyListUI;
    public boxEmoji!: Laya.Box;
    public listEmoji!: Laya.List;
}

