/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/chat/chatCell.lh
 */
export class ChatCellUIBase extends Laya.Box {
    public imgHead!: Laya.Image;
    public labelName!: Laya.Label;
    public labelMsg!: Laya.Label;
}

