/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { ChatListPanelUI } from "./ChatListPanelUI";

/**
 * resources/prefab/chat/chat.lh
 */
export class ChatUIBase extends Laya.Dialog {
    public btnClose!: Laya.Button;
    public btnSend!: Laya.Button;
    public btnEmoji!: Laya.Button;
    public listPanel!: ChatListPanelUI;
    public inputMsg!: Laya.TextInput;
}

