/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

/**
 * resources/prefab/common/panel/panel.lh
 */
export class ChatListPanelUIBase extends Laya.Panel {}
