/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/chat/home-chat-cell.lh
 */
export class HomeChatCellUIBase extends Laya.Box {
    public labelMsgType!: Laya.Label;
    public labelMsg!: Laya.Label;
}

