/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/shop/shop-dialog.lh
 */
export class ShopUIBase extends Laya.Dialog {
    public Image!: Laya.Image;
    public itemList!: Laya.List;
    public labelConsume!: Laya.Label;
    public btnClose!: Laya.Button;
}

