/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { IconUI } from "../icon/IconUI";

/**
 * resources/prefab/shop/shop-item.lh
 */
export class ShopItemUIBase extends Laya.Box {
    public labelName!: Laya.Label;
    public labelConsume!: Laya.Label;
    public iconDrward!: IconUI;
}

