/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { IconUI } from "../icon/IconUI";
import { HSliderUI } from "../common/HSliderUI";

/**
 * resources/prefab/shop/shop-buy.lh
 */
export class ShopBuyUIBase extends Laya.Dialog {
    public Image!: Laya.Image;
    public btnClose!: Laya.Button;
    public btnSynthesis!: Laya.Button;
    public icon!: IconUI;
    public labelName!: Laya.Label;
    public labelItemCurNum!: Laya.Label;
    public labelItemDesc!: Laya.Label;
    public slider!: HSliderUI;
    public labelNum!: Laya.Label;
}

