/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { IconUI } from "../icon/IconUI";

/**
 * resources/prefab/shop/shop-buy-dialog.lh
 */
export class ShopBuyUIBase extends Laya.Dialog {
    public Image!: Laya.Image;
    public closeBtn!: Laya.Button;
    public synthesisBtn!: Laya.Button;
    public iconNodeTop!: IconUI;
    public itemName!: Laya.Label;
    public labelItemNum!: Laya.Label;
    public labelItemDesc!: Laya.Label;
    public slider!: Laya.HSlider;
    public selectNumber!: Laya.Label;
    public haveNumber!: Laya.Label;
    public minusBtn!: Laya.Button;
    public addBtn!: Laya.Button;
}

