/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/shop/shop.lh
 */
export class ShopUIBase extends Laya.Dialog {
    public Image!: Laya.Image;
    public listItem!: Laya.List;
    public btnClose!: Laya.Button;
}

