/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { IconUI } from "../icon/IconUI";

/**
 * resources/prefab/shop/shop-buy.lh
 */
export class ShopBuyUIBase extends Laya.Dialog {
    public Image!: Laya.Image;
    public btnClose!: Laya.Button;
    public btnSynthesis!: Laya.Button;
    public iconNodeTop!: IconUI;
    public labelName!: Laya.Label;
    public labelNum!: Laya.Label;
    public labelItemDesc!: Laya.Label;
    public slNum!: Laya.HSlider;
    public selectNumber!: Laya.Label;
    public minusBtn!: Laya.Button;
    public addBtn!: Laya.Button;
}

