export const BattleConf = {
    ACTION_CD: 1,
    BATTLE_MODE: {
        DEFEND: 2,
        PK: 1,
        WORLD: 3,
    },
    BATTLE_TYPE: {
        PVE: 1,
        PVP: 2,
    },
    BORDER: {
        BOTTOM: -150,
        LEFT: -150,
        RIGHT: 150,
        TOP: 150,
    },
    CARD_SLOT_COUNT: 3,
    COMMAND: {
        ADD_BUFF: 6,
        ADD_ENTITY: 1,
        ATTACK: 9,
        DEL_BUFF: 8,
        DEL_ENTITY: 3,
        DROP_COIN: 11,
        FORCE_TO: 14,
        FORWARD: 16,
        MOVE_START: 4,
        MOVE_STOP: 5,
        MOVE_TO: 13,
        RECOVER_HP: 17,
        RETREAT: 15,
        UNDER_ATK: 10,
        UPDATE_CARD: 12,
        UPDATE_ENTITY: 2,
    },
    ENTITY_TYPE: {
        BUILDING: 5,
        BULLET: 4,
        FOOD: 7,
        HERO: 1,
        MONSTER: 3,
        SOLDIER: 2,
        STONE: 8,
        WOOD: 6,
    },
    LARGE_SCENE_ID: 2,
    LOGIC_FPS: 10,
    MAX_CARD_CARRY: 8,
    RECOVER_HP: 1,
    RECOVER_INTERVAL_MS: 100,
    RECOVER_WIDTH_RANGE: 100,
    SAME_ALLIANCE_LIMIT: 2,
    SIDE: {
        LEFT: -1,
        RIGHT: 1,
    },
    SIZE: {
    },
    SKILL_TYPE: {
        ATTACK: 0,
        SKILL: 1,
        TALENT: 2,
    },
    SMALL_SCENE_ID: 1,
    TEST_PVE_WAR_ID: 2,
    TEST_PVP_WAR_ID: 1,
    VISUAL_FPS: 60,
    WAR_FORMATION: {
        LINE: 1,
        SQUARE: 2,
    },
}
