export const WorldConf = {
    COM_ENUM: {
        BAG: "bag",
        BATTLE: "battle",
        BUILDING: "building",
        ITEM: "item",
        MOVE: "move",
        OWNER: "owner",
        PLAYER: "player",
        POS: "pos",
        STATE: "state",
        TROOP: "troop",
    },
    ENTITY_ACTION: {
        ADD_BOX: 12,
        ADD_ENTITY: 1,
        BATTLE_ADD_BUFF: 6,
        BATTLE_ADD_BULLET: 10,
        BATTLE_DEL_BUFF: 7,
        BATTLE_SKILL: 4,
        BATTLE_START: 8,
        BATTLE_STOP: 9,
        BATTLE_SUB_HP: 5,
        CHANGE_OWNER: 11,
        DEL_ENTITY: 2,
        DROP_BOX: 13,
        INVITE_SOLDIER: 15,
        MOVE: 3,
        PICK_ITEM: 14,
    },
    ENTITY_CMD: {
        MOVE_TO: 1,
        RETREAT: 3,
        STOP: 2,
    },
    ENTITY_COMPONENTS: {
        1: {
            1: "pos",
            2: "owner",
            3: "building",
        },
        2: {
            1: "pos",
            2: "state",
            3: "move",
            4: "owner",
            5: "troop",
        },
        4: {
            1: "player",
        },
        5: {
            1: "pos",
            2: "battle",
        },
        6: {
            1: "pos",
            2: "state",
            3: "move",
            4: "owner",
            5: "troop",
        },
        7: {
            1: "pos",
            2: "item",
        },
        8: {
            1: "pos",
            2: "building",
            3: "owner",
        },
        9: {
            1: "pos",
        },
        10: {
            1: "pos",
            2: "building",
        },
        11: {
            1: "pos",
            2: "item",
            3: "owner",
        },
    },
    ENTITY_STATE: {
        FIGHTING: 5,
        IDLE: 2,
        MOVE: 3,
        RETREAT: 6,
        STANDBY: 1,
        WAITLIST: 4,
    },
    ENTITY_TYPE: {
        BATTLE: 5,
        BOX: 7,
        CAMP: 8,
        CASTLE: 1,
        CITY: 3,
        DROP_ITEM: 11,
        MINE: 10,
        MONSTER: 6,
        PLAYER: 4,
        SOLDIER: 9,
        TROOP: 2,
    },
    LOGIC_FPS: 10,
    MOVE_TYPE: {
        DEGREE: 2,
        MOVE_TO: 1,
    },
    SAND_WORLD_ID: 101,
    VISUAL_FPS: 60,
}
