/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { IconUI } from "../icon/IconUI";

/**
 * resources/prefab/chest/chest-hero.lh
 */
export class ChestHeroUIBase extends Laya.Dialog {
    public listItem!: Laya.List;
    public iconNode!: IconUI;
}

