/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/chest/chest.lh
 */
export class ChestUIBase extends Laya.Box {
    public btnBoxReward!: Laya.Button;
    public labelBoxDesc!: Laya.Label;
    public btnOpenBox!: Laya.Button;
    public listBox!: Laya.List;
    public Sprite!: Laya.Sprite;
    public boxHero!: Laya.Box;
    public spineHero!: Laya.SpineSkeleton;
    public spineShest!: Laya.SpineSkeleton;
}

