/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/chest/chest.lh
 */
export class ChestUIBase extends Laya.Box {
    public labelBoxDesc!: Laya.Label;
    public btnOpenBox!: Laya.Button;
    public listBox!: Laya.List;
    public boxReward!: Laya.Box;
    public imgShestReward!: Laya.Image;
    public spineShestReward!: Laya.SpineSkeleton;
    public labelScore!: Laya.Label;
    public boxHero!: Laya.Box;
    public spineHero!: Laya.SpineSkeleton;
    public spineShest!: Laya.SpineSkeleton;
}

