/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/chest/chest-item.lh
 */
export class ChestItemUIBase extends Laya.Box {
    public imgIcon!: Laya.Image;
    public imgHigh!: Laya.Image;
    public labelNum!: Laya.Label;
}

