/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/login/login-server-list.lh
 */
export class LoginServerListUIBase extends Laya.Dialog {
    public itemList!: Laya.List;
    public listItemBox!: Laya.Box;
    public Button!: Laya.Button;
}

