/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { ImageBar } from "../../misc/ImageBar";

/**
 * resources/prefab/task/task-item-box.lh
 */
export class TaskItemBoxBase extends Laya.Box {
    public boxInfo!: Laya.Image;
    public btnUse!: Laya.Button;
    public imgBtnTipsGo!: Laya.Image;
    public imgBtnTipsUser!: Laya.Image;
    public labelDesc!: Laya.Label;
    public imgBar!: ImageBar;
    public labelBarVal!: Laya.Label;
    public imgIcon!: Laya.Image;
    public imgTips!: Laya.Image;
    public labelTips!: Laya.Label;
}

