/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/task/task.lh
 */
export class TaskUIBase extends Laya.Dialog {
    public btnClose!: Laya.Button;
    public listTask!: Laya.List;
}

