/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/task/task-item-box.lh
 */
export class TaskItemBoxBase extends Laya.Box {
    public btnUse!: Laya.Button;
    public labelDesc!: Laya.Label;
    public labelName!: Laya.Label;
}

