/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { VirtuallyListNewUI } from "../common/VirtuallyListNewUI";

/**
 * resources/prefab/task/task.lh
 */
export class TaskUIBase extends Laya.Dialog {
    public btnClose!: Laya.Button;
    public listTask!: Laya.List;
    public listTaskNew!: VirtuallyListNewUI;
}

