/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/icon/icon-node.lh
 */
export class IconUIBase extends Laya.Box {
    public iconBg!: Laya.Image;
    public iconQuality!: Laya.Image;
    public iconImage!: Laya.Image;
    public iconRedPoint!: Laya.Image;
    public iconNumber!: Laya.Label;
}

