/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/icon/icon.lh
 */
export class IconUIBase extends Laya.Box {
    public imgIBg!: Laya.Image;
    public imgQuality!: Laya.Image;
    public imgIcon!: Laya.Image;
    public imgRedPoint!: Laya.Image;
    public labelNumber!: Laya.Label;
}

