/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { IconUI } from "./IconUI";
import { ImageBar } from "../../misc/ImageBar";

/**
 * resources/prefab/icon/soldier-icon.lh
 */
export class SoldierIconUIBase extends Laya.Box {
    public icon!: IconUI;
    public imgBar!: ImageBar;
    public labelNum!: Laya.Label;
    public selectBox!: Laya.Image;
}

