/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/gm/gm-dialog.lh
 */
export class GmUIBase extends Laya.Dialog {
    public closeBtn!: Laya.Button;
    public textInput!: Laya.TextInput;
    public useBtn!: Laya.Button;
    public List!: Laya.List;
    public Label!: Laya.Label;
    public resetBtn!: Laya.Button;
}

