/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/gm/gm.lh
 */
export class GmUIBase extends Laya.Dialog {
    public btnClose!: Laya.Button;
    public textInput!: Laya.TextInput;
    public btnUse!: Laya.Button;
    public listEdict!: Laya.List;
    public Label!: Laya.Label;
    public btnReset!: Laya.Button;
}

