/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/gm/gm.lh
 */
export class GmUIBase extends Laya.Dialog {
    public textInput!: Laya.TextInput;
    public btnUse!: Laya.Button;
    public btnReset!: Laya.Button;
    public Tab!: Laya.Tab;
    public ViewStack!: Laya.ViewStack;
    public listSwitch!: Laya.List;
    public Label!: Laya.Label;
    public listGm!: Laya.List;
    //public Label!: Laya.Label;
}

