/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/alliance/alliance.lh
 */
export class AllianceUIBase extends Laya.Dialog {
    public btnClose!: Laya.Button;
    public btnConfirm!: Laya.Button;
    public radioGroup!: Laya.RadioGroup;
}

