/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/misc/alert.lh
 */
export class AlertUIBase extends Laya.Dialog {
    public title!: Laya.Label;
    public content!: Laya.Label;
    public btnOK!: Laya.Button;
    public btnNO!: Laya.Button;
}

