/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * scenes/main.ls
 */
export class MainSceneUIBase extends Laya.Scene {
    public btnBag!: Laya.Button;
}

