/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/mail/mail-info-dialog.lh
 */
export class MailInfoUIBase extends Laya.Dialog {
    public Image!: Laya.Image;
    public itemList!: Laya.List;
    public btnClose!: Laya.Button;
    public labelTitle!: Laya.Label;
    public labelContent!: Laya.Label;
    public btnDelete!: Laya.Button;
    public labelFrom!: Laya.Label;
    public labelDeliveryTime!: Laya.Label;
    public btnReceive!: Laya.Button;
}

