/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/mail/mail-dialog.lh
 */
export class MailUIBase extends Laya.Dialog {
    public Image!: Laya.Image;
    public menuTab!: Laya.Tab;
    public itemList!: Laya.List;
    public btnClose!: Laya.Button;
    public btnReward!: Laya.Button;
    public btnDelete!: Laya.Button;
}

