/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/battle/ui/head-info2.lh
 */
export class HeadInfoUIBase extends Laya.Box {
}

