/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { ImageBar } from "../../misc/ImageBar";

/**
 * resources/prefab/battle/ui/head-info1.lh
 */
export class HeadInfoUIBase extends Laya.Box {
    public hp!: ImageBar;
    public mp!: ImageBar;
}

