/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { ImageBar } from "../../misc/ImageBar";

/**
 * resources/prefab/battle/ui/hero-info.lh
 */
export class HeroInfoUIBase extends Laya.Box {
    public avatar!: Laya.Image;
    public hpBar!: ImageBar;
    public mpBar!: ImageBar;
    public hpTxt!: Laya.Label;
    public heroName!: Laya.Label;
}

