/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/battle/ui/hero-info.lh
 */
export class HeroInfoUIBase extends Laya.Box {
    public hp!: Laya.Image;
    public label!: Laya.Label;
}

