/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { ImageBar } from "../../misc/ImageBar";

/**
 * resources/prefab/battle/ui/soldier-info.lh
 */
export class SoldierInfoUIBase extends Laya.Box {
    public hpBar!: ImageBar;
}

