/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/common/list/testNode.lh
 */
export class TestNodeUIBase extends Laya.Box {
    public Label!: Laya.Label;
}

