/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { IconUI } from "../icon/IconUI";

/**
 * resources/prefab/bag/bag.lh
 */
export class BagUIBase extends Laya.Dialog {
    public tabMenu!: Laya.Tab;
    public listItem!: Laya.List;
    public iconNode!: IconUI;
    public btnClose!: Laya.Button;
}

