/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/bag/bag-dialog.lh
 */
export class BagUIBase extends Laya.Dialog {
    public menuTab!: Laya.Tab;
    public itemList!: Laya.List;
    public Button!: Laya.Button;
}

