/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { IconUI } from "../icon/IconUI";

/**
 * resources/prefab/bag/item-box-use.lh
 */
export class ItemBoxUseUIBase extends Laya.Dialog {
    public Image!: Laya.Image;
    public btnClose!: Laya.Button;
    public btnSynthesis!: Laya.Button;
    public iconNodeTop!: IconUI;
    public labelName!: Laya.Label;
    public labelDesc!: Laya.Label;
    public slNum!: Laya.HSlider;
    public selectNumber!: Laya.Label;
    public haveNumber!: Laya.Label;
    public minusBtn!: Laya.Button;
    public addBtn!: Laya.Button;
    public listItem!: Laya.List;
}

