/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/bag/item-synthesis.lh
 */
export class ItemSynthesisUIBase extends Laya.Dialog {
    public Image!: Laya.Image;
    public btnClose!: Laya.Button;
    public btnUse!: Laya.Button;
    public iconDown!: Laya.Box;
    public iconTop!: Laya.Box;
    public labelName!: Laya.Label;
    public labelDesc!: Laya.TextArea;
    public hsl!: Laya.HSlider;
    public haveNumber!: Laya.Label;
    public selectNumber!: Laya.Label;
}

