/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { IconUI } from "../icon/IconUI";
import { HSliderUI } from "../common/HSliderUI";

/**
 * resources/prefab/bag/item-box-use.lh
 */
export class ItemBoxUseUIBase extends Laya.Dialog {
    public Image!: Laya.Image;
    public btnClose!: Laya.Button;
    public btnSynthesis!: Laya.Button;
    public iconNodeTop!: IconUI;
    public labelName!: Laya.Label;
    public labelDesc!: Laya.Label;
    public listItem!: Laya.List;
    public slider_h!: HSliderUI;
}

