/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { IconUI } from "../icon/IconUI";

/**
 * resources/prefab/bag/item-tips-dialog.lh
 */
export class ItemTipsUIBase extends Laya.Dialog {
    public Sprite!: Laya.Sprite;
    public Image!: Laya.Image;
    public icon!: IconUI;
    public ItemName!: Laya.Label;
    public itemNumber!: Laya.Label;
    public itemDesc!: Laya.TextArea;
}

