/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { IconUI } from "../icon/IconUI";

/**
 * resources/prefab/bag/item-box-use-dialog.lh
 */
export class ItemBoxUseUIBase extends Laya.Dialog {
    public Image!: Laya.Image;
    public closeBtn!: Laya.Button;
    public synthesisBtn!: Laya.Button;
    public iconNodeTop!: IconUI;
    public itemName!: Laya.Label;
    public itemDesc!: Laya.TextArea;
    public slider!: Laya.HSlider;
    public selectNumber!: Laya.Label;
    public haveNumber!: Laya.Label;
    public minusBtn!: Laya.Button;
    public addBtn!: Laya.Button;
    public itemList!: Laya.List;
}

