/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { IconUI } from "../icon/IconUI";

/**
 * resources/prefab/bag/item-tips.lh
 */
export class ItemTipsUIBase extends Laya.Dialog {
    public Sprite!: Laya.Sprite;
    public Image!: Laya.Image;
    public iconItem!: IconUI;
    public labelName!: Laya.Label;
    public labelNumber!: Laya.Label;
    public labelDesc!: Laya.TextArea;
}

