/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { HomeDownBtnItemUI } from "./HomeDownBtnItemUI";

/**
 * resources/prefab/home/down-btn-box_new.lh
 */
export class HomeDownBtnBoxNewUIBase extends Laya.Box {
    public btnFight!: HomeDownBtnItemUI;
    public btnSoldier!: HomeDownBtnItemUI;
    public btnMain!: HomeDownBtnItemUI;
    public btnChest!: HomeDownBtnItemUI;
    public btnUnion!: HomeDownBtnItemUI;
}

