/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/home/user-box.lh
 */
export class HomeUserBoxUIBase extends Laya.Box {
    public imgHeadIcon!: Laya.Image;
    public labelName!: Laya.Label;
    public labelPower!: Laya.Label;
    public labelLv!: Laya.Label;
    public progressBarExp!: Laya.ProgressBar;
    public labelExp!: Laya.Label;
}

