/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/home/down-btn-item.lh
 */
export class HomeDownBtnItemUIBase extends Laya.Box {
    public imgIcon!: Laya.Image;
    public imgText!: Laya.Image;
    public selectBox!: Laya.Image;
}

