/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/home/navi-menu-btn.lh
 */
export class HomeNaviMenuBtnUIBase extends Laya.Box {
    public imgIcon!: Laya.Image;
    public imgText!: Laya.Image;
    public selectBox!: Laya.Image;
    public imgSelectBox!: Laya.Image;
}

