/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/home/down-btn-box.lh
 */
export class HomeDownBtnBoxUIBase extends Laya.Box {
    public listDownBtn!: Laya.List;
}

