/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { HomeMonyeItemUI } from "./HomeMonyeItemUI";

/**
 * resources/prefab/home/user-box.lh
 */
export class HomeUserBoxUIBase extends Laya.Box {
    public labelName!: Laya.Label;
    public imgHeadIcon!: Laya.Image;
    public labelPower!: Laya.Label;
    public moneyDiamond!: HomeMonyeItemUI;
    public moneyCoin!: HomeMonyeItemUI;
}

