/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { HomeNaviMenuBtnUI } from "./HomeNaviMenuBtnUI";

/**
 * resources/prefab/home/navi-menu.lh
 */
export class HomeNaviMenuUIBase extends Laya.Box {
    public btnFight!: HomeNaviMenuBtnUI;
    public btnSoldier!: HomeNaviMenuBtnUI;
    public btnMain!: HomeNaviMenuBtnUI;
    public btnChest!: HomeNaviMenuBtnUI;
    public btnUnion!: HomeNaviMenuBtnUI;
}
