/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * ../src/ui-runtime/prefab/home/boxTask.lh
 */
export class HomeTaskBoxUIBase extends Laya.Box {
    public imgIcon!: Laya.Image;
    public ProgressBar!: Laya.ProgressBar;
    public labelDesc!: Laya.Label;
    public labelValue!: Laya.Label;
}

