/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/home/task-box.lh
 */
export class HomeTaskBoxUIBase extends Laya.Box {
    public imgIcon!: Laya.Image;
    public labelDesc!: Laya.Label;
    public labelValue!: Laya.Label;
}

