/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/common/money/money-item.lh
 */
export class HomeMonyeItemUIBase extends Laya.Box {
    public imgIcon!: Laya.Image;
    public labelNum!: Laya.Label;
}

