/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/home/right-menu.lh
 */
export class HomeRightMenuUIBase extends Laya.Box {
    public imgClose!: Laya.Image;
    public btnRank!: Laya.Box;
    public btnBag!: Laya.Box;
    public btnShop!: Laya.Box;
    public btnNotice!: Laya.Box;
}

