/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/home/activity-box.lh
 */
export class HomeActivityBoxUIBase extends Laya.Box {
    public listActivity!: Laya.List;
}

