/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/home/boxMonye.lh
 */
export class HomeMonyeBoxUIBase extends Laya.Box {
    public listMonye!: Laya.List;
}

