/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * scenes/creator-role.ls
 */
export class CreatorRoleUIBase extends Laya.Scene {
    public tab!: Laya.Tab;
    public viewStack!: Laya.ViewStack;
    public btnCreatorRole!: Laya.Button;
    public textInputName!: Laya.TextInput;
    public btnRandomName!: Laya.Button;
}

