/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { HomeTaskBoxUI } from "../prefab/home/HomeTaskBoxUI";

/**
 * scenes/home.ls
 */
export class HomeUIBase extends Laya.Scene {
    public btnMail!: Laya.Button;
    public btnShop!: Laya.Button;
    public btnNotice!: Laya.Button;
    public boxTask!: HomeTaskBoxUI;
    public imgHeadIcon!: Laya.Image;
    public labelName!: Laya.Label;
    public labelPower!: Laya.Label;
    public labelLv!: Laya.Label;
    public progressBarExp!: Laya.ProgressBar;
    public labelExp!: Laya.Label;
    public boxChat!: Laya.Box;
    public labelMsg!: Laya.Label;
    public btnBag!: Laya.Button;
    public btnWorld!: Laya.Button;
}

