/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * scenes/home.ls
 */
export class HomeUIBase extends Laya.Scene {
    public btnBag!: Laya.Button;
    public btnTask!: Laya.Button;
    public btnMail!: Laya.Button;
    public btnShop!: Laya.Button;
    public btnNotice!: Laya.Button;
    public btnWorld!: Laya.Button;
}

