/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { HomeTaskBoxUI } from "../prefab/home/HomeTaskBoxUI";
import { HomeChatBoxUI } from "../prefab/home/HomeChatBoxUI";
import { HomeNaviMenuUI } from "../prefab/home/HomeNaviMenuUI";

/**
 * scenes/home.ls
 */
export class HomeUIBase extends Laya.Scene {
    public battle!: Laya.Box;
    public bg!: Laya.Image;
    public btnPve!: Laya.Button;
    public btnMail!: Laya.Button;
    public btnShop!: Laya.Button;
    public btnNotice!: Laya.Button;
    public btnBag!: Laya.Button;
    public btnEdge!: Laya.Button;
    public task_box!: HomeTaskBoxUI;
    public chat_box!: HomeChatBoxUI;
    public boxUI!: Laya.Box;
    public naviMenu!: HomeNaviMenuUI;
}

