/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * scenes/login.ls
 */
export class LoginUIBase extends Laya.Scene {
    public imgBg!: Laya.Image;
    public btnLogin!: Laya.Button;
    public btnServer!: Laya.Button;
    public labelServerName!: Laya.Label;
    public inputAccount!: Laya.TextInput;
}

