/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * scenes/pve.ls
 */
export class PveUIBase extends Laya.Scene {
    public debug!: Laya.Sprite;
    public troops!: Laya.Box;
    public labels!: Laya.Box;
    public joystickGroup!: Laya.Box;
    public joystick!: Laya.Box;
    public indicator!: Laya.Image;
}

