/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * scenes/pvp.ls
 */
export class PvpUIBase extends Laya.Scene {
    public debug!: Laya.Sprite;
    public troops!: Laya.Box;
    public labels!: Laya.Box;
    public mapClickArea!: Laya.Box;
}

