/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * scenes/world.ls
 */
export class WorldUIBase extends Laya.Scene {
    public joystickGroup!: Laya.Box;
    public joystick!: Laya.Box;
    public indicator!: Laya.Image;
}

