/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * scenes/app.ls
 */
export class appBase extends Laya.Scene {
    public Button!: Laya.Button;
    public Button2!: Laya.Button;
}

