/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/troop/troop-item.lh
 */
export class TroopItemUIBase extends Laya.Box {
    public selectBox!: Laya.Sprite;
    public VBox!: Laya.VBox;
    public btn1!: Laya.Button;
    public btn2!: Laya.Button;
    public btn3!: Laya.Button;
    public btn4!: Laya.Button;
}

