/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/troop/troop-item.lh
 */
export class TroopItemUIBase extends Laya.Sprite {
    public selectBox!: Laya.Sprite;
    public VBox!: Laya.VBox;
}

