/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { ListUI } from "../common/ListUI";

/**
 * resources/prefab/troop/troop.lh
 */
export class TroopUIBase extends Laya.Dialog {
    public listTroop!: ListUI;
    public listSoldier!: Laya.List;
}

