/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { ListUI } from "../common/ListUI";

/**
 * resources/prefab/troop/troop-pendant.lh
 */
export class TroopPendantUIBase extends Laya.Dialog {
    public listTroopPendant!: ListUI;
    public box!: Laya.Box;
    public selectBox!: Laya.Sprite;
    public btn!: Laya.Button;
    public listPendant!: ListUI;
}

