/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/common/slider/slider-h.lh
 */
export class HSliderUIBase extends Laya.HSlider {
    public minBtn!: Laya.Button;
    public addBtn!: Laya.Button;
}

