/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { IconUI } from "../icon/IconUI";

/**
 * resources/prefab/common/reward-dialog/reward.lh
 */
export class RewardUIBase extends Laya.Dialog {
    public listItem!: Laya.List;
    public iconNode!: IconUI;
}

