/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/common/list/virtually-list-new.lh
 */
export class VirtuallyListUIBase extends Laya.Box {
}

